version: '3.4'

services:
  mongo_db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  mongo_express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_db
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      - mongo_db

  server:
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
    depends_on:
      - mongo_db

volumes:
  mongo-data:
    driver: local